### ISSUE TITLE
Airlocks rotated 90 degrees and missing door frames for non-hosting clients (NEEDS CONFIRMATION)

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#186] opened 2020-04-21 20:13 UTC
### Summary

Airlocks seem to be rotated 90 degrees on the vertical axis, and the door frames are missing for non-hosting clients.

THIS SHOULD BE CONFIRMED BEFORE MOVING FORWARD.

### Steps to Reproduce

- Build game, and run 2 instances.
- Host from one, and join from the other.
- Check for any rotated airlocks form the non-hosting client.

### Context

[VIDEO](https://streamable.com/3sbopv)

**Comment by TimFinucane** [comment] 2020-05-02 04:31
Could not reproduce this. However, I do notice that a client does not see doors open, even though they can open them (if the client tries to open a door, the host sees the door open, but the door remains closed for the client).

**Comment by cosmiccoincidence** [comment] 2020-05-02 20:15
Hmm, so doors are not properly networked in the project currently? I noticed this as well when play testing PR #182 (not merged yet) and presumed it was caused by that PR, but it seems the issue was already in the project...

**Comment by TimFinucane** [comment] 2020-05-06 09:54
Closing as cannot reproduce. No longer seems to be a problem.

**Closed by TimFinucane** 2020-05-06 09:54 UTC
Labels: bug
