### ISSUE TITLE
Networking object state synchronization failure

### ISSUE THREAD

**Issue by cosmiccoincidence** [RE-SS3D/SS3D#215] opened 2020-05-09 05:45 UTC
### Summary

1. Joining players don't see open airlocks as open.
2. Items also bug out for joining players.

### Steps to Reproduce

1:
- Host a game
- Open an airlock
- Quickly join via 2nd client and observe airlock

2:
- Host game
- Join via 2nd client few moments later and notice some items bugged below tables or tipped over...

![image](https://user-images.githubusercontent.com/41941008/85809607-866aae00-b726-11ea-8d53-c97a3054e252.png)

Note: this seems to be all aspects of the game.

**Comment by henkhooft** [comment] 2021-07-08 18:11
Also related to the tilemap

**Comment by Ryan089** [comment] 2021-07-12 12:19
I was not able to reproduce the error for the items, and this is likely resolved by the NetworkTransform component on the items. The tilemap related issues will be dealt with in the tilemap rework.

**Closed** 2021-08-21 05:43 UTC
Labels: Type: Bug (Confirmed), Coding: C#, Priority: 2 - High, Difficulty: 3 - Rocket Science, System: Networking
